# Generated by Django 2.2.4 on 2020-12-07 20:01

import phonenumbers
from django.db import migrations


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except phonenumbers.NumberParseException:
            break
        if phonenumbers.is_valid_number(pure_phonenumber):
            flat.owner_pure_phone = pure_phonenumber
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers)
    ]
