# Generated by Django 2.2.4 on 2020-12-07 21:02

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={'phonenumber': flat.owners_phonenumber}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201207_2343'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
