# Generated by Django 2.2.4 on 2020-12-07 21:18

from django.db import migrations


def link_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={'phonenumber': flat.owners_phonenumber}
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20201208_0002'),
    ]

    operations = [
        migrations.RunPython(link_owners)
    ]
